# Generated by Django 6.0.3 on 2026-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('investment', 'Investment'), ('food', 'Food'), ('rent', 'Rent'), ('travel', 'Travel'), ('shopping', 'Shopping')], max_length=50),
        ),
    ]
